(function(){
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const state={correct:0,attempts:0,sound:false,step:-1,subnet:null,lab:null};
const layers=[[7,"Aplicación","Datos","Servicios de usuario: HTTP, DNS y SMTP."],[6,"Presentación","Datos","Formato, compresión y cifrado; es una abstracción OSI."],[5,"Sesión","Datos","Coordina diálogos; TCP/IP agrupa esta función."],[4,"Transporte","Segmento / datagrama","Puertos y comunicación proceso a proceso."],[3,"Red","Paquete","IP lógico y enrutamiento entre redes."],[2,"Enlace","Trama","MAC local y FCS dentro de un enlace."],[1,"Física","Bits","Señales eléctricas, ópticas o de radio."]];
const qs=[["Un router recibe una trama. ¿Qué consulta para elegir la siguiente red?","La IP destino del paquete","La MAC destino","El puerto TCP","El router toma la decisión con la IP destino del paquete."],["¿Cómo se llama normalmente la PDU de TCP?","Segmento","Trama","Paquete","TCP usa segmentos; UDP se denomina datagrama."],["Antes de enviar una trama Ethernet local, ¿qué necesita conocer el emisor?","La MAC del siguiente salto","La tabla BGP","El puerto físico","ARP permite resolver IPv4 a MAC dentro del enlace."],["¿Qué ocurre con la MAC al pasar por un router?","Se reemplaza en cada enlace","No cambia hasta el destino","Se convierte en IP","Cada salto crea una trama nueva."],["¿Cuál afirmación es correcta?","TLS se asocia conceptualmente a presentación, pero TCP/IP no la separa","TLS es siempre capa 6","ARP enruta paquetes IP","OSI es conceptual; las implementaciones TCP/IP no coinciden uno a uno."]];
function update(){ $("#session-score").textContent=state.correct;$("#session-progress").style.width=(state.attempts?state.correct/state.attempts*100:0)+"%";$("#session-detail").textContent=state.attempts?state.correct+" de "+state.attempts+" respuestas correctas en esta sesión.":"Elige un laboratorio para comenzar."}
function score(ok){state.attempts++;if(ok)state.correct++;update()}
function go(id){$$(".view").forEach(x=>x.classList.toggle("active",x.id===id));$$(".nav-link").forEach(x=>x.classList.toggle("active",x.dataset.view===id));scrollTo({top:0,behavior:"smooth"})}$$("[data-view]").forEach(x=>x.onclick=()=>go(x.dataset.view));$$("[data-go]").forEach(x=>x.onclick=()=>go(x.dataset.go));
$("#sound-toggle").onclick=e=>{state.sound=!state.sound;e.currentTarget.setAttribute("aria-pressed",state.sound);e.currentTarget.setAttribute("aria-label",state.sound?"Silenciar sonidos":"Activar sonidos")};
function num(ip){return ip.split(".").reduce((a,x)=>a*256+Number(x),0)>>>0}function ip(n){return [24,16,8,0].map(x=>(n>>>x)&255).join(".")}function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a}function msk(c){return (0xffffffff<<(32-c))>>>0}
function newSubnet(){let lv=$("#subnet-level").value,c=lv==="beginner"?[24,25,26][rnd(0,2)]:lv==="intermediate"?rnd(20,30):rnd(16,30),base=lv==="challenge"?[[10,rnd(0,255),rnd(0,255)],[172,rnd(16,31),rnd(0,255)],[192,168,rnd(0,255)]][rnd(0,2)]:[192,168,rnd(1,30)],host=base.concat(rnd(1,254)),n=num(host.join(".")),network=(n&msk(c))>>>0,broad=(network+Math.pow(2,32-c)-1)>>>0;state.subnet={c:c,n:network,b:broad};$("#subnet-problem").textContent=host.join(".")+" /"+c;$("#subnet-context").textContent="Calcula red, primer y último host, y broadcast. "+(Math.pow(2,32-c)-2)+" hosts utilizables.";$$(".answer-grid input").forEach(x=>{x.value="";x.className=""});$("#subnet-feedback").textContent="";$("#subnet-hint-box").classList.add("hidden")}
function hint(){let a=state.subnet,o=Math.floor((a.c-1)/8),mo=(msk(a.c)>>>((3-o)*8))&255;$("#subnet-hint-box").innerHTML="<strong>Pista:</strong> octeto "+(o+1)+", máscara <strong>"+mo+"</strong>, bloque <strong>"+(256-mo)+"</strong>. La red inicia en <strong>"+ip(a.n)+"</strong>.";$("#subnet-hint-box").classList.remove("hidden")}
function checkSubnet(){let a=state.subnet,w={network:ip(a.n),first:ip(a.n+1),last:ip(a.b-1),broadcast:ip(a.b)},ids={network:"#answer-network",first:"#answer-first",last:"#answer-last",broadcast:"#answer-broadcast"},good=0;Object.keys(ids).forEach(k=>{let e=$(ids[k]),ok=e.value.trim()===w[k];e.className=ok?"correct":"wrong";if(ok)good++});score(good===4);let f=$("#subnet-feedback");f.className="feedback "+(good===4?"good":"bad");f.textContent=good===4?"¡Excelente! Calculaste toda la subred correctamente.":"Tienes "+good+"/4. Revisa la pista y vuelve a intentarlo."}
$("#new-subnet").onclick=newSubnet;$("#subnet-level").onchange=newSubnet;$("#subnet-hint").onclick=hint;$("#check-subnet").onclick=checkSubnet;
function stacks(active,receiver){let h=receiver?$("#receiver-stack"):$("#sender-stack");h.textContent="";layers.forEach(l=>{let e=document.createElement("div");e.className="layer"+(active===l[0]?" active":"");e.innerHTML="<span>"+l[0]+". "+l[1]+"</span><b>"+l[2]+"</b>";h.append(e)})}
function part(t,c){let e=document.createElement("span");e.className="pdu-part "+c;e.textContent=t;return e}
function renderOSI(){let seq=[7,6,5,4,3,2,1,0,1,2,3,4,5,6,7],s=state.step,l=seq[s],box=$("#pdu-visual"),msg=$("#osi-message").value.trim()||"Datos de aplicación",title="Datos",dir="LISTO PARA ENCAPSULAR",desc="Avanza paso a paso para observar cómo se añaden o retiran encabezados.";stacks(s>=0&&s<=6?l:null,false);stacks(s>=8?l:null,true);box.textContent="";if(s===7){title="Bits";dir="MEDIO FÍSICO";desc="La trama se codifica como señales por cobre, fibra o radio.";box.append(part("01010010 01000101 01000100","bits"))}else if(s>=0&&s<=6){let x=layers[7-l];title=x[2];dir="EMISOR · CAPA "+l;desc=x[3];if(l<=2)box.append(part("MAC","mac"));if(l===2)box.append(part("FCS","fcs"));if(l<=3)box.append(part("IP","ip"));if(l<=4)box.append(part("TCP / UDP","tcp"));box.append(part(msg,"app"))}else if(s>=8){let x=layers[7-l];title=x[2];dir="RECEPTOR · CAPA "+l;desc=l===2?"Se valida FCS y se retira la trama; queda el paquete IP.":l===3?"Se procesa IP destino y se entrega a transporte.":l===4?"Los puertos entregan datos al proceso correcto.":x[3];box.append(part(l<2?"MAC retirado":"MAC","mac"));if(l<3)box.append(part("IP retirado","ip"));if(l<4)box.append(part("TCP / UDP retirado","tcp"));box.append(part(msg,"app"))}$("#pdu-name").textContent=title;$("#osi-direction").textContent=dir;$("#osi-explanation").textContent=desc;$("#osi-insight").innerHTML="<h3>"+title+"</h3><p>"+desc+"</p>"}
$("#osi-step").onclick=()=>{state.step=state.step>=14?0:state.step+1;renderOSI()};$("#osi-reset").onclick=()=>{state.step=-1;renderOSI()};$("#osi-message").oninput=renderOSI;
let used=[];function showQ(){if(used.length===qs.length)used=[];let n;do{n=rnd(0,qs.length-1)}while(used.includes(n));used.push(n);let q=qs[n],wrap=$("#osi-options");$("#osi-question").textContent=q[0];wrap.textContent="";$("#osi-quiz-feedback").textContent="";$("#osi-quiz-feedback").className="feedback";$("#next-osi-question").classList.add("hidden");[q[1],q[2],q[3]].sort(()=>Math.random()-.5).forEach(o=>{let b=document.createElement("button");b.textContent=o;b.onclick=()=>{let ok=o===q[1];Array.from(wrap.children).forEach(x=>{x.disabled=true;if(x.textContent===q[1])x.classList.add("correct")});if(!ok)b.classList.add("wrong");score(ok);let f=$("#osi-quiz-feedback");f.className="feedback "+(ok?"good":"bad");f.textContent=(ok?"¡Correcto! ":"Aún no. ")+q[4];$("#next-osi-question").classList.remove("hidden")};wrap.append(b)})}$("#next-osi-question").onclick=showQ;
function newLab(){let c=[24,25,26,27][rnd(0,3)],n=num("192.168."+rnd(1,20)+".0")&msk(c),z=Math.pow(2,32-c),same=Math.random()>.5,src=n+rnd(2,z-3),dst=same?n+rnd(2,z-3):n+z+rnd(2,z-3);state.lab={same:same};$("#lab-source").textContent=ip(src);$("#lab-destination").textContent=ip(dst);$("#lab-prefix").textContent="Ambos hosts usan máscara /"+c+". Calcula su red antes de decidir.";$("#lab-followup").classList.add("hidden");$("#lab-feedback").textContent="";$$(".integrated-card .options button").forEach(x=>{x.disabled=false;x.className=""})}
$("#lab-network-options").onclick=e=>{let b=e.target.closest("button");if(!b)return;let ok=(b.dataset.answer==="same")===state.lab.same;Array.from($("#lab-network-options").children).forEach(x=>x.disabled=true);score(ok);b.className=ok?"correct":"wrong";let f=$("#lab-feedback");f.className="feedback "+(ok?"good":"bad");f.textContent=ok?(state.lab.same?"Correcto: Host A resuelve la MAC de Host B y envía una trama local.":"Correcto: Host A envía la trama hacia la MAC del gateway."):"No exactamente. Aplica la máscara a ambas IP y compara las redes." ;$("#lab-followup").classList.remove("hidden")};
$("#lab-pdu-options").onclick=e=>{let b=e.target.closest("button");if(!b)return;let ok=b.dataset.answer==="packet";Array.from($("#lab-pdu-options").children).forEach(x=>{x.disabled=true;if(x.dataset.answer==="packet")x.className="correct"});if(!ok)b.className="wrong";score(ok);let f=$("#lab-feedback");f.className="feedback "+(ok?"good":"bad");f.textContent+=(ok?" El router consulta IP destino del paquete y crea una nueva trama para el siguiente enlace.":" El router decide principalmente usando la IP destino del paquete.")};
$("#new-lab").onclick=newLab;newSubnet();renderOSI();showQ();newLab();update()
})();